FROM php

WORKDIR /app

# Install xdebug
RUN pecl install xdebug \
  && docker-php-ext-enable xdebug

# Install Git, requirement for some Composer packages
RUN apt-get update && apt-get install -y \
  zip \
  git 
  
# Download and enable composer globally
RUN php -r "copy('https://getcomposer.org/download/1.6.5/composer.phar', 'composer.phar');"
RUN chmod +x composer.phar
RUN mv composer.phar /usr/local/bin/composer
RUN composer self-update

COPY composer.json ./
COPY composer.lock ./

# Get all the packages
RUN composer install
RUN composer dump-autoload -o