language: php
php:
  - '7.2'
  - '7.1'

before_install:
- composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
- composer install --dev

before_script: composer dump-autoload -o

script: 
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --bootstrap vendor/autoload.php backend/core/tests/
 
after_script:
- php vendor/bin/coveralls -v