language: php
php:
  - '7.2'
  - '7.1'

before_script: composer dump-autoload -o

script: 
  - phpunit

after_success:
  - travis_retry php bin/php-coveralls
  # or enable logging
  - travis_retry php bin/php-coveralls -v