version: '3'
services:
  backend:
    # image: php
    build: 
      context: .
      dockerfile: ./docker/backend/dockerfile
    volumes:
     - .:/app
     - /app/vendor
     - /app/bin
    # ports:
    #  - "5000:5000"
